version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: sample-cake-dusk-app
    volumes:
      - .:/sample-cake-dusk-app

  web:
    image: nginx:1.17.1-alpine
    container_name: sample-cake-dusk-web
    ports:
      - "9000:80"
    volumes:
      - .:/sample-cake-dusk-app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    build:
      context: ./docker/mysql
    container_name: sample-cake-dusk-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data:
